# Site settings
author: Norberto Santiago
title: The Over Due Dream 
header-img: img/home-bg.png
email: norbertosantiago82@gmail.com
copyright_name: Norberto Santiago
description: > # this means to ignore newlines until "baseurl:"
  From Giving Up to Getting Up With Codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: norbert_82
github_username:  N-Santiago

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
