# Site settings
author: Norberto Santiago
title: My Unexpected Journey: From Giving Up to Getting Up With Codes
header-img: img/home-bg.png
email: norbertosantiago82@gmail.com
copyright_name: Norberto Santiago
description: > # this means to ignore newlines until "baseurl:"
  Doing what many told me I can't do. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  N-Santiago

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
